# name: Deploy for Docker Hub
# on: 
#     push:
#         branches: ['main']
# jobs:
#     teste-run:
#         runs-on: ${{ matrix.os }}
#         strategy:
#             matrix:
#                 os: ['ubuntu-latest']
                
#         env:
#             tag: 'teste'
#             name: 'django-app-teste'
#         steps:
#             - uses: actions/checkout@v5

#             - name: Build Aplication
#               run: docker compose build

#             - name: List Build
#               run: docker images


#     deploy:
#         needs: teste-run
#         runs-on: ${{ matrix.os }}
#         environment: Docker
#         env:
#             tag: ${{ github.sha }}
#             name: 'django-app'
#         strategy:
#             matrix:
#                 os: ['ubuntu-latest']
#         steps:
#             - uses: actions/checkout@v5

#             - name: Add User and Password
#               uses: docker/login-action@v3
#               with:
#                   username: ${{ secrets.USERNAME }}
#                   password: ${{ secrets.PASSWORD }}

#             - name: Build Image
#               run: |
#                   docker compose build --push

#             - name: Push image for Docker Hub
#               run: |
#                   docker push falace/${{ env.name }}:${{ env.tag }}
    manifest:
        needs: deploy
        runs-on: ubuntu-latest
        environment: GIT-SSH
        steps:
            - name: Add SSH Key
              uses: webfactory/ssh-agent@v0.9.0
              with: 
                  ssh-private-key: ${{ secrets.SSH_AGENT }}
            - name: Add for GitHub
              run: |
                  mkdir Pasta
                  git init Pasta/
                  git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git config --global user.name "github-actions[bot]"
                  git clone git@github.com:alexsandroocanha/Django-DevOps-Pipeline-Manifest.git Pasta/
                  cat > ~/Pasta/deployment-k8s.yml <<EOF
                      Bazinga
                  EOF
                  cd Pasta
                  git add .
                  git commit -m "${{ github.sha }}"
                  git push -u origin master
                  
        
