name: Deploy Python
on: 
    push:
        branches: ['main', 'dev/ci']
jobs:
    teste-run:
        runs-on: ${{ matrix.os }}
        env:
            tag: 'teste'
        steps:
            - uses: actions/checkout@v5

            - name: Build Aplication
              run: docker compose build

            - name: List Build
              run: docker images

    deploy:
        env:
            tag: ${{ github.sha }}
        runs-on: ${{ matrix.os }}
        environment: Docker
        strategy:
            matrix:
                os: ['ubuntu-latest']
        steps:
            - uses: actions/checkout@v5

            - name: Add User and Password
              uses: docker/login-action@v3
              with:
                  username: ${{ secrets.USERNAME }}
                  password: ${{ secrets.PASSWORD }}

            - name: Build Image
              run: |
                  docker compose build --push

            - name: Push image for Docker Hub
              run: |
                  docker push falace/django-app:latest
