name: Deploy Python
on: 
  pull_request: 
    branches: ['main', 'test']
jobs:
    teste-run:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                os: ['ubuntu-latest']
                
        env:
            tag: 'teste'
            name: 'django-app-teste'
        steps:
            - uses: actions/checkout@v5

            - name: Build Aplication
              run: docker compose build

            - name: List Build
              run: docker images
